// File generated by FlutterFire CLI with dev overrides.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Development Firebase options loaded from environment variables.
/// 
/// Use with: flutter run -t lib/main_dev.dart --dart-define-from-file=.dart_define.dev.json
class DefaultFirebaseOptionsDev {
  static const String _webApiKey =
      String.fromEnvironment('DEV_FIREBASE_WEB_API_KEY');
  static const String _webAppId =
      String.fromEnvironment('DEV_FIREBASE_WEB_APP_ID');
  static const String _messagingSenderId =
      String.fromEnvironment('DEV_FIREBASE_MESSAGING_SENDER_ID');
  static const String _projectId =
      String.fromEnvironment('DEV_FIREBASE_PROJECT_ID');
  static const String _authDomain =
      String.fromEnvironment('DEV_FIREBASE_AUTH_DOMAIN');
  static const String _storageBucket =
      String.fromEnvironment('DEV_FIREBASE_STORAGE_BUCKET');
  static const String _databaseUrl =
      String.fromEnvironment('DEV_FIREBASE_DATABASE_URL');
  static const String _measurementId =
      String.fromEnvironment('DEV_FIREBASE_MEASUREMENT_ID');

  static FirebaseOptions get currentPlatform {
    _validate(
      platform: 'web',
      values: {
        'DEV_FIREBASE_WEB_API_KEY': _webApiKey,
        'DEV_FIREBASE_WEB_APP_ID': _webAppId,
        'DEV_FIREBASE_MESSAGING_SENDER_ID': _messagingSenderId,
        'DEV_FIREBASE_PROJECT_ID': _projectId,
        'DEV_FIREBASE_AUTH_DOMAIN': _authDomain,
        'DEV_FIREBASE_STORAGE_BUCKET': _storageBucket,
        'DEV_FIREBASE_DATABASE_URL': _databaseUrl,
      },
    );
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: _webAppId,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    authDomain: _authDomain,
    storageBucket: _storageBucket,
    databaseURL: _databaseUrl,
    measurementId: _measurementId,
  );

  static void _validate({
    required String platform,
    required Map<String, String> values,
  }) {
    final missing = values.entries
        .where((entry) => entry.value.trim().isEmpty)
        .map((entry) => entry.key)
        .toList();

    if (missing.isNotEmpty) {
      throw UnsupportedError(
        'Missing dev Firebase dart-defines for $platform: ${missing.join(', ')}. '
        'Run: ./scripts/setup-dev-defines.ps1 -Target web',
      );
    }
  }
}
